# SPDX-FileCopyrightText: 2024 Luflosi <zonegen@luflosi.de>
# SPDX-License-Identifier: CC0-1.0

[licenses]
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "BSL-1.0",
  "GPL-3.0-only",
  "MIT",
  "Unicode-3.0",
  "Zlib",
]
